language: node_js
os:
  - linux
node_js:
  - "lts/*"
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn install
  - yarn lint
  - yarn type-check
  - yarn md-lint
  - if [ "$TRAVIS_BRANCH" -eq "release" ] && ["$TRAVIS_EVENT_TYPE" -eq "pull_request"]; then yarn lh https://blog-staging.rayriffy.com/ fi
